config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "acme/omniauth_callbacks", registrations: "acme/registrations" }
 resources :recipes do
 	resources :reviews
	 	collection do 
	 		get 'my'
 	end
 end
 
 root 'recipes#index'




end

app/models/recipe.rb
class Recipe < ApplicationRecord

belongs_to :user
belongs_to :category
has_many :reviews

has_attached_file :image, styles: { medium: "400x400>" }
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

has_many :ingredients, inverse_of: :recipe
has_many :directions, inverse_of: :recipe

accepts_nested_attributes_for :ingredients, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true

accepts_nested_attributes_for :directions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true								

validates :title, :description, :image, presence: true

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :find_recipe, only: [:show, :edit, :update, :destroy] 
before_action :authenticate_user!, except: [:index, :show]

	def index
		@search = Recipe.search(params[:q])

		if params[:category].blank?
			@recipe = @search.result.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@recipe = Recipe.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def my
		@recipe = current_user.recipes.order("created_at DESC")
		render :index
	end

	def show
		if @recipe.reviews.blank?
			@average_review = 0
		else
			@average_review = @recipe.reviews.average(:rating).round(2)
		end
	end

	def new
		@recipe = current_user.recipes.build
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)
		@recipe.category_id = params[:category_id]
			if @recipe.save
				redirect_to @recipe, notice: "Successfully created new recipe"
			else
				render 'new'
			end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def update
		@recipe.category_id = params[:category_id]
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, :category_id, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end






end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category")
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/_search.html.haml
= search_form_for @search do |f|
	= f.label :title_cont, "search" 
	= f.text_field :title_cont

	= f.submit

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
= render 'search'
%h3= params[:category]
%br

- if @recipe.count == 0
	%h4 There are no recipes currently in this category
- else
- @recipe.each_slice(3) do |recipe|
	.row
		- recipe.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							=image_tag recipe.image.url(:medium)
					%h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p
					Submitted by
					= @recipe.user.email				
				%p 	
					Category:
					= @recipe.category.name				
				%h4 Average Rating
				.average-review-rating{"data-score" => @average_review}
				%span Based on #{ @recipe.reviews.count} reviews
				
				%p.description= @recipe.description



	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ol
					- @recipe.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-6
			#reviews
				%h3 Reviews
				= render @recipe.reviews
					
				= link_to "Back", root_path, class: "btn btn-default"
					- if user_signed_in?
					= link_to "Add Review", new_recipe_review_path(@recipe), class: "btn btn-default"
					- if current_user.id == @recipe.user_id
						= link_to "Edit", edit_recipe_path, class: "btn btn-default"
						= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"

:javascript
	$('.review-rating').raty({
	  	readOnly: true,
	  	score: function() {
	  		return $(this).attr('data-score');
	  	},
	  	path: '/assets/'
	  });

:javascript
	$('.average-review-rating').raty({
	  	readOnly: true,
	  	path: '/assets/',
	  	score: function() {
	  		return $(this).attr('data-score')
	  	}
	  });