config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "acme/omniauth_callbacks", registrations: "acme/registrations" }
 resources :recipes do
 	resources :reviews
	 	collection do 
	 		get 'my'
 	end
 end
 
 root 'recipes#index'




end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_recipe
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.recipe_id = @recipe.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to recipe_path(@recipe)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to recipe_path(@recipe)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to recipe_path(@recipe)
	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def find_recipe
		@recipe = Recipe.find(params[:recipe_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= simple_form_for([@recipe, @recipe.reviews.build]) do |f|
	- if @review.errors.any?
		#errors
			%p
				= @review.errors.count
				Prevented this review froms saving
			%ul
				- @review.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		#rating-form
			%label Rating
		= f.input :comment, input_html: { class: 'form-control' }	
		= f.button :submit, class: "btn btn-primary"

:javascript
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});

app/views/reviews/_review.html.haml
.review-rating{"data-score" => "#{review.rating}"}

%p Comment by #{review.user.email}
%p= review.comment

- if user_signed_in?
	- if current_user.id == review.user_id
		= link_to "Edit", edit_recipe_review_path(review.recipe, review)
		= link_to "Delete", recipe_review_path(review.recipe, review), method: :delete, data: {confirm: "Are you sure?"}

app/views/reviews/edit.html.haml
%h3 Edit Review

= simple_form_for([@recipe, @review]) do |f|
	- if @review.errors.any?
		#errors
			%p
				= @review.errors.count
				Prevented this review froms saving
			%ul
				- @review.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		#rating-form
			%label Rating
		= f.input :comment, input_html: { class: 'form-control' }	
		= f.button :submit, class: "btn btn-primary"

:javascript
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});

app/views/reviews/new.html.haml
%h1 New Review

= render 'form'