config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "acme/omniauth_callbacks", registrations: "acme/registrations" }
 resources :recipes do
 	resources :reviews
	 	collection do 
	 		get 'my'
 	end
 end
 
 root 'recipes#index'




end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Best Recipe
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Best Recipes", root_path
			

			%ul.nav.navbar-nav.navbar-right
				%li.dropdown
					%a.dropdown-toggle{:href => "#", :role => "button", "aria-expanded" => "false", "data-toggle" => "dropdown"}
						Categories
						%span.caret
					%ul.dropdown-menu{"role" => "menu"}
						- Category.all.each do |category|
							%li
								= link_to category.name, recipes_path(category: category.name)

				- if user_signed_in?
				
					%li= link_to "My Recipes", my_recipes_path
					%li= link_to "New Recipe", new_recipe_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
				
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path

			


	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"

		= yield